language: python
python:
  - 2.7

services:
  - docker

sudo: true

install:
  - docker build -t server-image .
  - docker run -itd -v "$(pwd)":/web -p 8000:8000 --name sphinx-server server-image
  - sudo arp -d 172.17.0.2

script:
  - docker ps | grep -q sphinx-server
  - docker exec -it sphinx-server sphinx-quickstart -q -p test -a tester -v 0.1
  - docker exec -it sphinx-server make html
  - curl -O http://localhost:8000/index.html
  - grep -q "Welcome to test’s documentation!" index.html
  - docker exec -it sphinx-server plantuml -v
